[project]
name = "innomightlabs-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dependency-injector>=4.48.2",
    "langchain-aws>=0.2.35",
    "prompt-toolkit>=3.0.52",
    "rich>=14.1.0",
]
